#!/bin/bash
#
#------------------------------------------------
#
# Author: 		Marc Zimmermann
# create date: 	19.02.2016
# 
#
# History:
#	19.02.2016 - Initial Version, creation
#


#DEFINITIONS


#FUNCTIONS
